export interface ColorToken {
  key: string;
  name: string;
  variable: string;
  tailwindClass: string;
  lightHex: string;
  lightHcHex?: string;
  darkHex?: string;
  darkHcHex?: string;
  category: 'backdrop' | 'theme' | 'surface' | 'container' | 'outline' | 'selection' | 'status' | 'link';
  categoryLabel: string;
  description: string;
}

export const COLOR_TOKENS: ColorToken[] = [
  // 1. Backdrop Category
  {
    key: 'cm.sys.color.backdrop',
    name: 'Backdrop',
    variable: '--cm-sys-color-backdrop',
    tailwindClass: 'bg-cm-backdrop / text-cm-backdrop',
    lightHex: '#F0F5FE',
    lightHcHex: '#E6ECF7',
    darkHex: '#282C32',
    darkHcHex: '#232831',
    category: 'backdrop',
    categoryLabel: 'Category: Backdrop',
    description: 'Shell background canvas for BigQuery Studio viewport',
  },
  {
    key: 'cm.sys.color.backdrop-active',
    name: 'Backdrop Active',
    variable: '--cm-sys-color-backdrop-active',
    tailwindClass: 'bg-cm-backdrop-active',
    lightHex: '#DBEDFC',
    lightHcHex: '#C7DBF6',
    darkHex: '#2A3F5E',
    darkHcHex: '#344B7A',
    category: 'backdrop',
    categoryLabel: 'Category: Backdrop',
    description: 'Selected state for icons, platform menu items background',
  },
  {
    key: 'cm.sys.color.backdrop-inset',
    name: 'Backdrop Inset',
    variable: '--cm-sys-color-backdrop-inset',
    tailwindClass: 'bg-cm-backdrop-inset',
    lightHex: '#DDE3EA',
    lightHcHex: '#D1D8E3',
    darkHex: '#4C4F5C',
    darkHcHex: '#2E333B',
    category: 'backdrop',
    categoryLabel: 'Category: Backdrop',
    description: 'Inset containers and secondary backdrop surfaces',
  },
  {
    key: 'cm.sys.color.on-backdrop-variant',
    name: 'On Backdrop Variant',
    variable: '--cm-sys-color-on-backdrop-variant',
    tailwindClass: 'text-cm-on-backdrop-variant',
    lightHex: '#545F72',
    lightHcHex: '#2D3A4F',
    darkHex: '#9CA6B2',
    darkHcHex: '#D3D4D6',
    category: 'backdrop',
    categoryLabel: 'Category: Backdrop',
    description: 'Icon default states, Cloud Logo stroke',
  },
  {
    key: 'cm.sys.color.on-backdrop',
    name: 'On Backdrop',
    variable: '--cm-sys-color-on-backdrop',
    tailwindClass: 'text-cm-on-backdrop',
    lightHex: '#1B2E5D',
    lightHcHex: '#0B1F44',
    darkHex: '#F1F4F9',
    darkHcHex: '#FFFFFF',
    category: 'backdrop',
    categoryLabel: 'Category: Backdrop',
    description: 'Text labels, platform bar icon selected state',
  },

  // 2. Theme Category
  {
    key: 'cm.sys.color.primary',
    name: 'Primary',
    variable: '--cm-sys-color-primary',
    tailwindClass: 'bg-cm-primary / text-cm-primary',
    lightHex: '#496CC3',
    lightHcHex: '#4058B5',
    darkHex: '#839CFF',
    darkHcHex: '#8FA8FF',
    category: 'theme',
    categoryLabel: 'Category: Theme',
    description: 'Use to color important/key elements. Example: Background of a primary flat button.',
  },
  {
    key: 'cm.sys.color.on-primary',
    name: 'On Primary',
    variable: '--cm-sys-color-on-primary',
    tailwindClass: 'text-cm-on-primary',
    lightHex: '#FFFFFF',
    lightHcHex: '#FFFFFF',
    darkHex: '#1B2E5D',
    darkHcHex: '#0B1F44',
    category: 'theme',
    categoryLabel: 'Category: Theme',
    description: 'Use to color text/icons on cm.sys.color.primary. Example: Label of a primary flat button.',
  },
  {
    key: 'cm.sys.color.primary-inverse',
    name: 'Primary Inverse',
    variable: '--cm-sys-color-primary-inverse',
    tailwindClass: 'bg-cm-primary-inverse',
    lightHex: '#839CFF',
    lightHcHex: '#8FA8FF',
    darkHex: '#496CC3',
    darkHcHex: '#4058B5',
    category: 'theme',
    categoryLabel: 'Category: Theme',
    description: 'Use to color key elements within inverse containers. Example: Background of a primary button in a snackbar.',
  },
  {
    key: 'cm.sys.color.on-primary-inverse',
    name: 'On Primary Inverse',
    variable: '--cm-sys-color-on-primary-inverse',
    tailwindClass: 'text-cm-on-primary-inverse',
    lightHex: '#1B2E5D',
    lightHcHex: '#0B1F44',
    darkHex: '#FFFFFF',
    darkHcHex: '#FFFFFF',
    category: 'theme',
    categoryLabel: 'Category: Theme',
    description: 'Use to color text/icons on cm.sys.color.primary-inverse. Example: Label of a primary inverse flat button.',
  },

  // 3. Surface Category
  {
    key: 'cm.sys.color.surface',
    name: 'Surface',
    variable: '--cm-sys-color-surface',
    tailwindClass: 'bg-cm-surface',
    lightHex: '#FFFFFF',
    lightHcHex: '#FFFFFF',
    darkHex: '#353B43',
    darkHcHex: '#2E333B',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Use to color the background of unelevated surfaces/containers. Example: Background of a main page panel.',
  },
  {
    key: 'cm.sys.color.on-surface',
    name: 'On Surface',
    variable: '--cm-sys-color-on-surface',
    tailwindClass: 'text-cm-on-surface',
    lightHex: '#1B2E5D',
    lightHcHex: '#0B1F44',
    darkHex: '#F1F4F9',
    darkHcHex: '#FFFFFF',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Use to color text/icons on surfaces/containers. Example: Paragraph on a main page panel.',
  },
  {
    key: 'cm.sys.color.surface-variant',
    name: 'Surface Variant',
    variable: '--cm-sys-color-surface-variant',
    tailwindClass: 'bg-cm-surface-variant',
    lightHex: '#F5F8FC',
    lightHcHex: '#EEF2F8',
    darkHex: '#3C444E',
    darkHcHex: '#35414F',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Use for secondary surface cards and elevated component containers.',
  },
  {
    key: 'cm.sys.color.on-surface-variant',
    name: 'On Surface Variant',
    variable: '--cm-sys-color-on-surface-variant',
    tailwindClass: 'text-cm-on-surface-variant',
    lightHex: '#475569',
    lightHcHex: '#203357',
    darkHex: '#B9C0CC',
    darkHcHex: '#E5E7EB',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Use to color less-important text/icons on surfaces. Example: Hint text underneath a form control.',
  },
  {
    key: 'cm.sys.color.on-surface-variant-low',
    name: 'On Surface Variant Low',
    variable: '--cm-sys-color-on-surface-variant-low',
    tailwindClass: 'text-cm-on-surface-variant-low',
    lightHex: '#7F919C',
    lightHcHex: '#5C6E7A',
    darkHex: '#ADB7C3',
    darkHcHex: '#C3CBD3',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Low-emphasis muted text, timestamps, and secondary placeholders.',
  },
  {
    key: 'cm.sys.color.surface-elevation',
    name: 'Surface Elevation',
    variable: '--cm-sys-color-surface-elevation',
    tailwindClass: 'bg-cm-surface-elevation',
    lightHex: '#F0F5FE',
    lightHcHex: '#E6ECF7',
    darkHex: '#282C32',
    darkHcHex: '#232831',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Elevated surfaces and floating dialog modal backdrops.',
  },
  {
    key: 'cm.sys.color.surface-inverse',
    name: 'Surface Inverse',
    variable: '--cm-sys-color-surface-inverse',
    tailwindClass: 'bg-cm-surface-inverse',
    lightHex: '#353B43',
    lightHcHex: '#2E333B',
    darkHex: '#FFFFFF',
    darkHcHex: '#FFFFFF',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Background of inverse surfaces/containers. Example: Background of a snackbar.',
  },
  {
    key: 'cm.sys.color.on-surface-inverse',
    name: 'On Surface Inverse',
    variable: '--cm-sys-color-on-surface-inverse',
    tailwindClass: 'text-cm-on-surface-inverse',
    lightHex: '#F1F4F9',
    lightHcHex: '#FFFFFF',
    darkHex: '#1B2E5D',
    darkHcHex: '#0B1F44',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Text/icons on inverse containers (e.g. snackbar text).',
  },
  {
    key: 'cm.sys.color.surface-modal',
    name: 'Surface Modal',
    variable: '--cm-sys-color-surface-modal',
    tailwindClass: 'bg-cm-surface-modal',
    lightHex: '#F5F8FC',
    lightHcHex: '#EEF2F8',
    darkHex: '#3C444E',
    darkHcHex: '#35414F',
    category: 'surface',
    categoryLabel: 'Category: Surface',
    description: 'Modal window container surface background.',
  },

  // 4. Container Category
  {
    key: 'cm.sys.color.container',
    name: 'Container',
    variable: '--cm-sys-color-container',
    tailwindClass: 'bg-cm-container',
    lightHex: '#E9EEF6',
    lightHcHex: '#D5DFED',
    darkHex: '#414D5E',
    darkHcHex: '#1F2C3A',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Standard container surface for card elements and input fields.',
  },
  {
    key: 'cm.sys.color.container-high',
    name: 'Container High',
    variable: '--cm-sys-color-container-high',
    tailwindClass: 'bg-cm-container-high',
    lightHex: '#DAE5F7',
    lightHcHex: '#C9D9F2',
    darkHex: '#2B3A50',
    darkHcHex: '#273A52',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Higher emphasis container surface for featured cards.',
  },
  {
    key: 'cm.sys.color.container-primary',
    name: 'Container Primary',
    variable: '--cm-sys-color-container-primary',
    tailwindClass: 'bg-cm-container-primary',
    lightHex: '#F5FBFF',
    lightHcHex: '#E9F2FF',
    darkHex: '#3D4A62',
    darkHcHex: '#3F4F7A',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Use to color the background of higher-importance containers. Example: Primary chip bg.',
  },
  {
    key: 'cm.sys.color.container-primary-outline',
    name: 'Container Primary Outline',
    variable: '--cm-sys-color-container-primary-outline',
    tailwindClass: 'border-cm-container-primary-outline',
    lightHex: '#DCEBFD',
    lightHcHex: '#9DB7E5',
    darkHex: '#506276',
    darkHcHex: '#7289A8',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Primary container outline border.',
  },
  {
    key: 'cm.sys.color.on-container',
    name: 'On Container',
    variable: '--cm-sys-color-on-container',
    tailwindClass: 'text-cm-on-container',
    lightHex: '#1B2E5D',
    lightHcHex: '#0B1F44',
    darkHex: '#E5ECFF',
    darkHcHex: '#EBF0FF',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Use to color text/icons on containers. Example: Message text of an info banner.',
  },
  {
    key: 'cm.sys.color.primary-on-container',
    name: 'Primary On Container',
    variable: '--cm-sys-color-primary-on-container',
    tailwindClass: 'text-cm-primary-on-container',
    lightHex: '#314F9B',
    lightHcHex: '#1F3A8A',
    darkHex: '#A8BAFF',
    darkHcHex: '#8FA8FF',
    category: 'container',
    categoryLabel: 'Category: Container',
    description: 'Use to color primary text/icons on containers. Example: Primary text button on colored surface.',
  },

  // 5. Outline / Hairline Category
  {
    key: 'cm.sys.color.hairline',
    name: 'Hairline',
    variable: '--cm-sys-color-hairline',
    tailwindClass: 'border-cm-hairline',
    lightHex: '#B7C3E0',
    lightHcHex: '#9FB0CF',
    darkHex: '#50638B',
    darkHcHex: '#6376A6',
    category: 'outline',
    categoryLabel: 'Category: Outline / Hairline',
    description: 'Use to color low-contrast or decorative borders. Example: Divider separating page regions.',
  },
  {
    key: 'cm.sys.color.outline',
    name: 'Outline',
    variable: '--cm-sys-color-outline',
    tailwindClass: 'border-cm-outline',
    lightHex: '#8496C1',
    lightHcHex: '#4B5EA3',
    darkHex: '#B7C2E8',
    darkHcHex: '#D6DEFF',
    category: 'outline',
    categoryLabel: 'Category: Outline / Hairline',
    description: 'Use to color high-contrast borders of interactive containers. Example: Border of a form field input.',
  },
  {
    key: 'cm.sys.color.outline-active',
    name: 'Outline Active',
    variable: '--cm-sys-color-outline-active',
    tailwindClass: 'border-cm-outline-active',
    lightHex: '#496CC3',
    lightHcHex: '#4058B5',
    darkHex: '#839CFF',
    darkHcHex: '#8FA8FF',
    category: 'outline',
    categoryLabel: 'Category: Outline / Hairline',
    description: 'Borders of interactive containers in active state. Example: Focused input border.',
  },
  {
    key: 'cm.sys.color.outline-focus',
    name: 'Outline Focus (Keyboard)',
    variable: '--cm-sys-color-outline-focus',
    tailwindClass: 'ring-cm-outline-focus',
    lightHex: '#4058B5',
    lightHcHex: '#314F9B',
    darkHex: '#A9B8FF',
    darkHcHex: '#B8C7FF',
    category: 'outline',
    categoryLabel: 'Category: Outline / Hairline',
    description: 'Keyboard accessibility focus outline ring.',
  },

  // 6. Selection Category
  {
    key: 'cm.sys.color.selection',
    name: 'Selection',
    variable: '--cm-sys-color-selection',
    tailwindClass: 'bg-cm-selection',
    lightHex: '#496CC3',
    lightHcHex: '#4058B5',
    darkHex: '#839CFF',
    darkHcHex: '#8FA8FF',
    category: 'selection',
    categoryLabel: 'Category: Selection',
    description: 'Use to color selected text/icons on a surface. Example: Color of a selected radio button.',
  },
  {
    key: 'cm.sys.color.selection-container',
    name: 'Selection Container',
    variable: '--cm-sys-color-selection-container',
    tailwindClass: 'bg-cm-selection-container',
    lightHex: '#E0F0F9',
    lightHcHex: '#CFE4F6',
    darkHex: '#3A4756',
    darkHcHex: '#2E4152',
    category: 'selection',
    categoryLabel: 'Category: Selection',
    description: 'Background of selected containers. Example: Background of a selected navigation item.',
  },

  // 7. Status Category
  {
    key: 'cm.sys.color.status.activeassist',
    name: 'Activeassist',
    variable: '--cm-sys-color-status-activeassist',
    tailwindClass: 'text-cm-status-activeassist',
    lightHex: '#0082ED',
    lightHcHex: '#005FCC',
    darkHex: '#4DA3FF',
    darkHcHex: '#6BB6FF',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Activeassist AI recommendation indicator.',
  },
  {
    key: 'cm.sys.color.status.activeassist-container',
    name: 'Activeassist Container',
    variable: '--cm-sys-color-status-activeassist-container',
    tailwindClass: 'bg-cm-status-activeassist-container',
    lightHex: '#E8F5FE',
    lightHcHex: '#D1E9FA',
    darkHex: '#344B63',
    darkHcHex: '#35506E',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Background of Activeassist AI recommendation cards.',
  },
  {
    key: 'cm.sys.color.status.success',
    name: 'Success',
    variable: '--cm-sys-color-status-success',
    tailwindClass: 'text-cm-status-success',
    lightHex: '#108463',
    lightHcHex: '#0E7A5E',
    darkHex: '#6EEBBF',
    darkHcHex: '#86E8C8',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Elements that communicate success or positive sentiment.',
  },
  {
    key: 'cm.sys.color.status.success-container',
    name: 'Success Container',
    variable: '--cm-sys-color-status-success-container',
    tailwindClass: 'bg-cm-status-success-container',
    lightHex: '#E5F7F6',
    lightHcHex: '#A7E6D7',
    darkHex: '#275F5C',
    darkHcHex: '#225956',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Background of success message banners and completed query tags.',
  },
  {
    key: 'cm.sys.color.status.warning',
    name: 'Warning',
    variable: '--cm-sys-color-status-warning',
    tailwindClass: 'text-cm-status-warning',
    lightHex: '#C64415',
    lightHcHex: '#983601',
    darkHex: '#FFDF82',
    darkHcHex: '#FFDF82',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Elements communicating warning sentiment (e.g. outdated asset badge).',
  },
  {
    key: 'cm.sys.color.status.warning-container',
    name: 'Warning Container',
    variable: '--cm-sys-color-status-warning-container',
    tailwindClass: 'bg-cm-status-warning-container',
    lightHex: '#FFF6D6',
    lightHcHex: '#FFE8A3',
    darkHex: '#736B3F',
    darkHcHex: '#6B5A1F',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Background of warning alert banners.',
  },
  {
    key: 'cm.sys.color.status.error',
    name: 'Error',
    variable: '--cm-sys-color-status-error',
    tailwindClass: 'text-cm-status-error',
    lightHex: '#C61F74',
    lightHcHex: '#A61F64',
    darkHex: '#FFB8DB',
    darkHcHex: '#FFADD8',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Elements communicating error or negative sentiment.',
  },
  {
    key: 'cm.sys.color.status.error-container',
    name: 'Error Container',
    variable: '--cm-sys-color-status-error-container',
    tailwindClass: 'bg-cm-status-error-container',
    lightHex: '#FFEFF2',
    lightHcHex: '#FAD1D8',
    darkHex: '#7D4560',
    darkHcHex: '#6F3148',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Background of error diagnostic banners.',
  },
  {
    key: 'cm.sys.color.status.destructive-container',
    name: 'Destructive Container',
    variable: '--cm-sys-color-status-destructive-container',
    tailwindClass: 'bg-cm-status-destructive-container',
    lightHex: '#D9257F',
    lightHcHex: '#B4236D',
    darkHex: '#B6213C',
    darkHcHex: '#9C1C33',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Destructive action container background.',
  },
  {
    key: 'cm.sys.color.status.neutral',
    name: 'Neutral',
    variable: '--cm-sys-color-status-neutral',
    tailwindClass: 'text-cm-status-neutral',
    lightHex: '#496CC3',
    lightHcHex: '#4058B5',
    darkHex: '#839CFF',
    darkHcHex: '#8FA8FF',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Elements communicating neutral info sentiment.',
  },
  {
    key: 'cm.sys.color.status.neutral-container',
    name: 'Neutral Container',
    variable: '--cm-sys-color-status-neutral-container',
    tailwindClass: 'bg-cm-status-neutral-container',
    lightHex: '#E9EEF6',
    lightHcHex: '#D8DFF0',
    darkHex: '#50638B',
    darkHcHex: '#3F4F7A',
    category: 'status',
    categoryLabel: 'Category: Status',
    description: 'Background of neutral informational banners.',
  },

  // 8. Link Category
  {
    key: 'cm.sys.color.link.default',
    name: 'Default Link',
    variable: '--cm-sys-color-link-default',
    tailwindClass: 'text-cm-link-default',
    lightHex: '#314F9B',
    lightHcHex: '#1F3A8A',
    darkHex: '#A8BAFF',
    darkHcHex: '#8FA8FF',
    category: 'link',
    categoryLabel: 'Category: Links',
    description: 'Hyperlink default text color.',
  },
];

export interface TypeToken {
  key: string;
  name: string;
  fontFamily: string;
  fontWeight: string;
  fontSize: string;
  lineHeight: string;
  category: 'display' | 'headline' | 'title' | 'label' | 'body' | 'code';
  description: string;
}

export const TYPE_TOKENS: TypeToken[] = [
  // 1. Display Category
  {
    key: 'cm.sys.type.display-large',
    name: 'Display Large',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '56px',
    lineHeight: '64px',
    category: 'display',
    description: 'Use to style large marketing blurbs or hero metrics on landing pages.',
  },
  {
    key: 'cm.sys.type.display-medium',
    name: 'Display Medium',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '44px',
    lineHeight: '52px',
    category: 'display',
    description: 'Use to style medium marketing blurbs or hero metrics on landing pages.',
  },
  {
    key: 'cm.sys.type.display-small',
    name: 'Display Small',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '36px',
    lineHeight: '44px',
    category: 'display',
    description: 'Use to style small marketing blurbs or hero metrics on landing pages.',
  },
  // 2. Headline Category
  {
    key: 'cm.sys.type.headline-large',
    name: 'Headline Large',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '40px',
    category: 'headline',
    description: 'Use to style large headings on product landing pages.',
  },
  {
    key: 'cm.sys.type.headline-medium',
    name: 'Headline Medium',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '36px',
    category: 'headline',
    description: 'Use to style medium headings on product landing pages.',
  },
  {
    key: 'cm.sys.type.headline-small',
    name: 'Headline Small',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '32px',
    category: 'headline',
    description: 'Use to style small headings on product landing page.',
  },
  // 3. Title Category
  {
    key: 'cm.sys.type.title-large',
    name: 'Title Large',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '22px',
    lineHeight: '28px',
    category: 'title',
    description: 'Use to style in-page, top-level headings. Example: Top-level heading on a Create page.',
  },
  {
    key: 'cm.sys.type.title-medium',
    name: 'Title Medium',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '24px',
    category: 'title',
    description: 'Use to style in-page, second-level headings. Example: Second-level heading on a Create page.',
  },
  {
    key: 'cm.sys.type.title-small',
    name: 'Title Small',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '24px',
    category: 'title',
    description: 'Use to style in-page, third-level headings or system headings. Example: System heading in an Action Bar.',
  },
  // 4. Label Category
  {
    key: 'cm.sys.type.label-large',
    name: 'Label Large',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
    category: 'label',
    description: 'Use to style in-page, fourth-level headings. Example: Sub-heading of a form on a Create page.',
  },
  {
    key: 'cm.sys.type.label-medium',
    name: 'Label Medium',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '20px',
    category: 'label',
    description: 'Use to style standard labels in containers. Example: Label in a button, tab, or table header.',
  },
  {
    key: 'cm.sys.type.label-small',
    name: 'Label Small',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '16px',
    category: 'label',
    description: 'Use to style small labels in containers. Example: Label in a menu or badge.',
  },
  // 5. Body Category
  {
    key: 'cm.sys.type.body-large',
    name: 'Body Large',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    category: 'body',
    description: 'Use to style large body text. Example: Large paragraph on a main page panel.',
  },
  {
    key: 'cm.sys.type.body-medium',
    name: 'Body Medium',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
    category: 'body',
    description: 'Use to style standard body text. Example: Standard paragraph on a main page panel.',
  },
  {
    key: 'cm.sys.type.body-small',
    name: 'Body Small',
    fontFamily: '"Google Sans Flex", sans-serif',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '16px',
    category: 'body',
    description: 'Use to style small captions. Example: Small caption on a main page panel.',
  },
  // 6. Code Category
  {
    key: 'cm.sys.type.code',
    name: 'Code',
    fontFamily: '"Roboto Mono", monospace',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '16px',
    category: 'code',
    description: 'Use to style code text. Example: Code text in a code snippet or code editor.',
  },
];

export interface ElevationToken {
  key: string;
  name: string;
  variable: string;
  tailwindClass: string;
  lightValue: string;
  lightHcValue?: string;
  darkValue?: string;
  darkHcValue?: string;
  category: 'shadow';
  description: string;
}

const ELEVATION_LIGHT =
  '0px 1px 2px 0px rgba(60,64,67,0.3), 0px 2px 6px 2px rgba(60,64,67,0.15)';
const ELEVATION_DARK = `${ELEVATION_LIGHT}, 0px 0px 0px 1px inset rgb(60,64,67)`;

export const ELEVATION_TOKENS: ElevationToken[] = [
  {
    key: 'cm.sys.elevation.shadow',
    name: 'Elevation Shadow',
    variable: '--cm-sys-elevation-shadow',
    tailwindClass: 'shadow-cm-elevation',
    lightValue: ELEVATION_LIGHT,
    lightHcValue: ELEVATION_LIGHT,
    darkValue: ELEVATION_DARK,
    darkHcValue: ELEVATION_DARK,
    category: 'shadow',
    description:
      'Lifts a surface off the canvas — menus, popovers, floating panels and raised cards. Dark themes add an inset hairline because the drop shadow alone is invisible against a dark surface.',
  },
];
